### PR TITLE
Implement distinct()

### PR DESCRIPTION
**Pull request by jpic**
This implementation of distinct() is simple and natural: call distinct() on all QuerySets of a QuerySetSequence.

### CODE REVIEW

**Comment by clokep** [comment]
> This implementation of distinct() is simple and natural: call distinct() on all QuerySets of a QuerySetSequence.

I think that this doesn't handle cases where:

* There are multiple `QuerySet` instances of the same type (you shouldn't really need to use `QuerySetSequence` for this anyway, but you can).
* A `values()` or `values_list()` call is made which causes the results to not be distinct, something like:

```pycon
>>> qss = QuerySetSequence(Book.objects.all(), Article.objects.all())
>>> qss = qss.values("pk")
>>> qss = qss.distinct()
>>> list(qss)
???
```

I'm not sure what the expected behavior in this case even really is, but I think you'd want `[1, 2, 3]`, not `[1, 2, 3, 1, 2, 3]`.

**Comment by jpic** [comment]
> There are multiple QuerySet instances of the same type (you shouldn't really need to use QuerySetSequence for this anyway, but you can).

Agreed, I don't think there's any value at all in supporting this use case neither.

> A values() or values_list() call is made which causes the results to not be distinct

That's still possible with `set(qss.values("pk"))`, the point of this distinct() implementation is just to allow filtering on m2m relations which otherwise would result in duplicated rows.

**Comment by clokep** [comment]
> The point of this distinct() implementation is just to allow filtering on m2m relations without duplicating rows, but any way other than defining distinct on the QSS would also work for us.

I don't think that this matches the definition of `distinct()` for a normal `QuerySet`. I'll need to re-read the docs though and see what they say.

**Comment by jpic** [comment]
I found this:

2020-11-24-220919_1082x247_scrot

And I was surprised myself because I thought the abstraction would be a bit at a higher level, but actually it seems logic that calling `qs.distinct()` means `SELECT DISTINCT`. If that's fine for the moment, it won't prevent anyone from contributing an implementation in Python in the future if they feel strongly about having QSS with different QS of the same model - as long as performance don't become disastrous which I would expect to be the case, not you ?

**Comment by jpic** [comment]
But I can add support for querysets of the same type easily, would you want to merge if I added like 4-5 SLOCS to make distinct() remove any duplicate result from any queryset that shares the model with a former queryset ? I have no use for that but if you do I will be more than happy to do it for you for free ;)

**Comment by clokep** [comment]
A decent interim might be to just raise an exception if any of the `QuerySet` instances are of the same time? At least the behavior will be clear. 😄

**Comment by jpic** [comment]
Done! Thank you so much @clokep :heart:

**Comment by clokep** [comment]
Thanks! 👍

**Pull request merged**
